import type { DocumentDetail, DocumentSummary } from "@/types";

export const MOCK_DOCUMENTS: DocumentSummary[] = [
  {
    id: "doc_falls_prev",
    title: "Falls Prevention & Post-Fall Management",
    shortTitle: "Falls Prevention",
    type: "policy",
    version: "4.2",
    status: "published",
    sectors: ["aged-care", "home-care"],
    rolesRelevant: ["registered-nurse", "care-worker", "team-leader"],
    tags: ["safety", "mobility", "high-priority"],
    category: "Clinical Safety",
    pillar: "Resident Safety",
    effectiveAt: "2025-04-10T00:00:00+10:00",
    updatedAt: "2025-05-12T00:00:00+10:00",
    bookmarked: true,
    pinnedAsQuickRef: true,
    offlineAvailable: true,
    recentlyUsedByAI: true,
    estimatedReadMinutes: 7,
    emergencyRelated: false,
  },
  {
    id: "doc_med_admin",
    title: "Medication Administration Standard",
    shortTitle: "Medication Admin",
    type: "procedure",
    version: "6.0",
    status: "updated",
    sectors: ["aged-care"],
    rolesRelevant: ["registered-nurse", "enrolled-nurse"],
    tags: ["clinical", "medication", "safety"],
    category: "Clinical Care",
    pillar: "Clinical Governance",
    effectiveAt: "2025-03-01T00:00:00+10:00",
    updatedAt: "2025-05-19T00:00:00+10:00",
    bookmarked: false,
    offlineAvailable: true,
    recentlyUsedByAI: true,
    estimatedReadMinutes: 12,
  },
  {
    id: "doc_sirs",
    title: "SIRS Reportable Incidents",
    type: "guideline",
    version: "3.1",
    status: "published",
    sectors: ["aged-care"],
    rolesRelevant: ["registered-nurse", "team-leader", "care-worker"],
    tags: ["compliance", "regulatory", "incident"],
    category: "Compliance",
    pillar: "Regulatory",
    effectiveAt: "2025-01-15T00:00:00+10:00",
    updatedAt: "2025-04-02T00:00:00+10:00",
    bookmarked: true,
    offlineAvailable: true,
    estimatedReadMinutes: 9,
    emergencyRelated: true,
  },
  {
    id: "doc_infection",
    title: "Infection Prevention & Outbreak Response",
    type: "procedure",
    version: "5.4",
    status: "published",
    sectors: ["aged-care", "retirement-living"],
    rolesRelevant: ["registered-nurse", "care-worker"],
    tags: ["infection", "outbreak", "ppe"],
    category: "Clinical Safety",
    effectiveAt: "2024-11-20T00:00:00+10:00",
    updatedAt: "2025-04-28T00:00:00+10:00",
    offlineAvailable: true,
    estimatedReadMinutes: 11,
    emergencyRelated: true,
  },
  {
    id: "doc_behaviour",
    title: "Responsive Behaviours De-escalation",
    type: "guideline",
    version: "2.7",
    status: "published",
    sectors: ["aged-care", "ndis"],
    rolesRelevant: ["care-worker", "support-worker", "registered-nurse"],
    tags: ["behaviour", "dementia", "psychosocial"],
    category: "Clinical Care",
    effectiveAt: "2025-02-08T00:00:00+10:00",
    updatedAt: "2025-05-04T00:00:00+10:00",
    bookmarked: true,
    estimatedReadMinutes: 8,
  },
  {
    id: "doc_skin_int",
    title: "Skin Integrity & Pressure Injury Prevention",
    type: "policy",
    version: "3.9",
    status: "published",
    sectors: ["aged-care"],
    rolesRelevant: ["registered-nurse", "enrolled-nurse", "care-worker"],
    tags: ["clinical", "wound"],
    category: "Clinical Care",
    effectiveAt: "2025-03-22T00:00:00+10:00",
    updatedAt: "2025-05-06T00:00:00+10:00",
    estimatedReadMinutes: 6,
  },
  {
    id: "doc_emerg_fire",
    title: "Fire Emergency Response Protocol",
    type: "emergency-protocol",
    version: "2.0",
    status: "published",
    sectors: ["aged-care", "retirement-living", "home-care"],
    rolesRelevant: [
      "registered-nurse",
      "care-worker",
      "team-leader",
      "support-worker",
    ],
    tags: ["emergency", "fire", "evacuation"],
    category: "Emergency",
    effectiveAt: "2025-01-01T00:00:00+10:00",
    updatedAt: "2025-04-15T00:00:00+10:00",
    pinnedAsQuickRef: true,
    offlineAvailable: true,
    estimatedReadMinutes: 4,
    emergencyRelated: true,
  },
  {
    id: "doc_consent",
    title: "Informed Consent Form",
    type: "form",
    version: "1.4",
    status: "published",
    sectors: ["aged-care", "ndis", "home-care"],
    rolesRelevant: ["registered-nurse", "team-leader"],
    tags: ["consent", "form"],
    category: "Documentation",
    effectiveAt: "2025-02-15T00:00:00+10:00",
    updatedAt: "2025-04-30T00:00:00+10:00",
    estimatedReadMinutes: 3,
  },
  {
    id: "doc_handover",
    title: "Clinical Handover Standard",
    type: "procedure",
    version: "2.2",
    status: "published",
    sectors: ["aged-care"],
    rolesRelevant: ["registered-nurse", "enrolled-nurse"],
    tags: ["clinical", "communication"],
    category: "Clinical Care",
    effectiveAt: "2025-02-12T00:00:00+10:00",
    updatedAt: "2025-04-10T00:00:00+10:00",
    estimatedReadMinutes: 5,
  },
];

export const MOCK_DOCUMENT_DETAIL: DocumentDetail = {
  ...MOCK_DOCUMENTS[0]!,
  summary:
    "Operational standard for falls prevention assessments, environmental controls, and post-fall escalation steps applicable to all residential and home-care contexts.",
  sections: [
    {
      id: "sec_intent",
      anchor: "intent",
      title: "Intent",
      body: "Reduce the frequency and severity of falls through proactive assessment, environmental controls, and rapid post-fall response.",
    },
    {
      id: "sec_scope",
      anchor: "scope",
      title: "Scope",
      body: "Applies to all clinical and care staff working with residents at risk of falling, including those in care, support, and clinical roles.",
    },
    {
      id: "sec_assess",
      anchor: "assessment",
      title: "Assessment",
      body: "Use the validated falls risk screen on admission, after any fall, and following any change in clinical condition. Document in the resident record.",
    },
    {
      id: "sec_response",
      anchor: "post-fall",
      title: "Post-fall response",
      body: "Do not move the resident until clinical assessment is complete. Notify the registered nurse on duty and document neurovascular observations every 30 minutes for 2 hours, then hourly for 4 hours.",
    },
    {
      id: "sec_escalation",
      anchor: "escalation",
      title: "Escalation",
      body: "Escalate to the team leader and on-call clinical lead for any head strike, suspected fracture, change in conscious state, or unwitnessed fall.",
    },
  ],
  guidedSteps: [
    {
      index: 1,
      title: "Ensure scene is safe",
      detail: "Check the immediate environment. Do not move the resident yet.",
      iconKey: "shield",
    },
    {
      index: 2,
      title: "Primary assessment",
      detail:
        "Assess airway, breathing, circulation and conscious state. Look for visible injuries or pain on movement.",
      iconKey: "stethoscope",
      caution: "Stop and call 000 immediately for any suspected severe injury.",
    },
    {
      index: 3,
      title: "Notify the RN",
      detail:
        "Page the registered nurse on duty. Provide location, witnessed status, mechanism, and observations.",
      iconKey: "phone",
    },
    {
      index: 4,
      title: "Begin neurovascular obs",
      detail:
        "Every 30 minutes for the first 2 hours; then hourly for 4 hours. Document each set.",
      iconKey: "activity",
    },
    {
      index: 5,
      title: "Lodge incident report",
      detail:
        "Submit the incident report within the same shift. Include all observations, witnesses, and immediate actions.",
      iconKey: "file-text",
    },
  ],
  relatedForms: [
    { id: "form_post_fall", title: "Post-Fall Observation Chart", type: "form" },
    { id: "form_incident", title: "Resident Incident Report", type: "form" },
  ],
  relatedFaqs: [
    {
      id: "faq_unwitnessed",
      title: "What if the fall was unwitnessed?",
      type: "faq",
    },
    {
      id: "faq_head_strike",
      title: "When must I escalate a head strike?",
      type: "faq",
    },
  ],
  hasEmergencyVariant: true,
  acknowledgementRequired: false,
};
