import type {
  CredentialItem,
  InductionStep,
  SignedDocument,
  TrainingModule,
} from "@/types";

export const MOCK_TRAINING: TrainingModule[] = [
  {
    id: "tr_med_safety",
    title: "Medication Safety Refresher",
    type: "module",
    category: "Clinical",
    durationMinutes: 25,
    status: "due-soon",
    progressPercent: 0,
    dueAt: "2025-05-30T00:00:00+10:00",
    rolesRelevant: ["registered-nurse", "enrolled-nurse"],
    linkedPolicyId: "doc_med_admin",
    required: true,
  },
  {
    id: "tr_falls",
    title: "Falls Prevention in Practice",
    type: "module",
    category: "Clinical",
    durationMinutes: 30,
    status: "in-progress",
    progressPercent: 60,
    dueAt: "2025-06-12T00:00:00+10:00",
    rolesRelevant: ["registered-nurse", "care-worker"],
    linkedPolicyId: "doc_falls_prev",
    required: true,
  },
  {
    id: "tr_dementia",
    title: "Responsive Behaviours: De-escalation",
    type: "microlearning",
    category: "Behavioural",
    durationMinutes: 8,
    status: "not-started",
    progressPercent: 0,
    rolesRelevant: ["care-worker", "support-worker"],
  },
  {
    id: "tr_hoist",
    title: "Safe Use of Mechanical Hoists",
    type: "video",
    category: "Manual Handling",
    durationMinutes: 6,
    status: "completed",
    progressPercent: 100,
    rolesRelevant: ["care-worker", "support-worker"],
  },
  {
    id: "tr_sirs",
    title: "SIRS Reportable Incidents",
    type: "module",
    category: "Compliance",
    durationMinutes: 20,
    status: "overdue",
    progressPercent: 30,
    dueAt: "2025-05-18T00:00:00+10:00",
    rolesRelevant: ["registered-nurse", "team-leader"],
    linkedPolicyId: "doc_sirs",
    required: true,
  },
  {
    id: "tr_consent",
    title: "Informed Consent — Quick Reference",
    type: "microlearning",
    category: "Documentation",
    durationMinutes: 4,
    status: "not-started",
    progressPercent: 0,
    rolesRelevant: ["registered-nurse", "team-leader"],
  },
];

export const MOCK_INDUCTION: InductionStep[] = [
  {
    id: "ind_1",
    index: 1,
    title: "Welcome & site orientation",
    status: "completed",
    durationMinutes: 12,
    type: "module",
  },
  {
    id: "ind_2",
    index: 2,
    title: "Code of conduct",
    status: "completed",
    durationMinutes: 10,
    type: "module",
  },
  {
    id: "ind_3",
    index: 3,
    title: "Clinical safety essentials",
    status: "current",
    durationMinutes: 22,
    type: "module",
  },
  {
    id: "ind_4",
    index: 4,
    title: "Emergency response drill",
    status: "upcoming",
    durationMinutes: 14,
    type: "competency",
  },
  {
    id: "ind_5",
    index: 5,
    title: "Final sign-off",
    status: "upcoming",
    durationMinutes: 6,
    type: "module",
  },
];

export const MOCK_SIGNED_DOCS: SignedDocument[] = [
  {
    id: "sig_1",
    documentId: "doc_med_admin",
    documentTitle: "Medication Administration Standard",
    version: "5.9",
    signedAt: "2025-02-21T09:14:00+10:00",
    signatureMethod: "typed",
  },
  {
    id: "sig_2",
    documentId: "doc_sirs",
    documentTitle: "SIRS Reportable Incidents",
    version: "3.0",
    signedAt: "2025-01-19T13:02:00+10:00",
    signatureMethod: "typed",
  },
];

export const MOCK_CREDENTIALS: CredentialItem[] = [
  {
    id: "cred_ahpra",
    name: "AHPRA Registration",
    issuer: "Nursing & Midwifery Board of AU",
    number: "NMW0001234567",
    issuedAt: "2024-05-31T00:00:00+10:00",
    expiresAt: "2025-05-31T00:00:00+10:00",
    status: "expiring-soon",
    required: true,
    fileName: "ahpra-2024.pdf",
  },
  {
    id: "cred_first_aid",
    name: "First Aid (HLTAID011)",
    issuer: "St John Ambulance",
    issuedAt: "2024-09-12T00:00:00+10:00",
    expiresAt: "2027-09-12T00:00:00+10:00",
    status: "valid",
    required: true,
  },
  {
    id: "cred_police",
    name: "National Police Check",
    issuer: "Australian Federal Police",
    issuedAt: "2024-04-02T00:00:00+10:00",
    expiresAt: "2027-04-02T00:00:00+10:00",
    status: "valid",
    required: true,
  },
  {
    id: "cred_nfd",
    name: "NDIS Worker Screening",
    issuer: "NDIS Quality and Safeguards",
    status: "in-review",
    required: true,
  },
];
